create table if not exists public.messages (
    id bigint generated by default as identity primary key,
    session_id uuid not null,
    filename text not null,
    question text not null,
    answer text not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_messages_session_id
    on public.messages(session_id);

alter table public.messages enable row level security;

drop policy if exists "messages_select_all" on public.messages;
create policy "messages_select_all"
on public.messages
for select
to public
using (true);

drop policy if exists "messages_insert_all" on public.messages;
create policy "messages_insert_all"
on public.messages
for insert
to public
with check (true);

drop policy if exists "messages_delete_session" on public.messages;
create policy "messages_delete_session"
on public.messages
for delete
to public
using (true);